fixtures:
  repositories:
    "stdlib": "ssh://git@github.com/cegeka/puppet-stdlib.git"
    "apt": "ssh://git@github.com/cegeka/puppet-apt.git"
    "concat": "ssh://git@github.com/cegeka/puppet-concat.git"
  symlinks:
    "rabbitmq": "#{source_dir}"
